apiVersion: v1
kind: Namespace
metadata:
  name: nfs-check

---
apiVersion: v1
kind: Pod
metadata:
  name: external-storage-access
  namespace: nfs-check
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: ubuntu:latest 
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: nfsvol
      mountPath: /opt
  volumes:
  - name: nfsvol
    persistentVolumeClaim: 
      claimName: nfs-check-data   

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-check-vol
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /kubernetes/data
    server: 172.31.7.244

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-check-data
  namespace: nfs-check
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

