# This is a ConfigMap definition for Nginx configuration file method
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: data
  labels:
    app: data
data: 
  webproxy.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        location /proxy {
            proxy_pass http://localhost:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    server {
        listen 82;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        location /proxy {
            proxy_pass http://localhost:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }


---
# config map key value pair example 
apiVersion: v1
kind: ConfigMap
metadata:
  name: keydata
  namespace: data
  labels:
    app: data
data:
  player_initial_lives: "3"
  configmap_file: "/etc/ngninx/conf.d/webproxy.conf"
  exposed_port: "80"
  proxy_port: "82"

