apiVersion: apps/v1
kind: Deployment
metadata:
  name: hogs
spec:
  selector:
    matchLabels:
      app: hogs
  template:
    metadata:
      labels:
        app: hogs
    spec:
      containers:
      - name: hogsapp
        image: vish/stress
        restartPolicy: Always    
        args: 
        - -cpus
        - "2"
        - -mem-total
        - "2000Mi"
        - -mem-alloc-size
        - "100Mi"
        - -mem-alloc-sleep
        - "1s"