apiVersion: v1
kind: Namespace
metadata:
  name: hogs
---
# LimitRange for Pod or Container
apiVersion: v1
kind: LimitRange
metadata:
  name: LimitRangeName
  namespace: hogs
spec:
  limits:
  - type: Container
    default:
      cpu: 100m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: 200m
      memory: 512Mi
    min:
      cpu: 100m
      memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hogs
  namespace: hogs
spec:
  selector:
    matchLabels:
      app: hogs
  template:
    metadata:
      labels:
        app: hogs
    spec:
      containers:
      - name: hogsapp
        image: vish/stress
        restartPolicy: Always    
        args: 
        - -cpus
        - "2"
        - -mem-total
        - "2000Mi"
        - -mem-alloc-size
        - "100Mi"
        - -mem-alloc-sleep
        - "1s"