apiVersion: apps/v1
kind: Deployment
metadata:
  name: hogs
spec:
  selector:
    matchLabels:
      app: hogs
  template:
    metadata:
      labels:
        app: hogs
    spec:
      containers:
      - name: hogsapp
        image: vish/stress
        restartPolicy: Always
        resources: 
          requests:
            memory: "1000Mi"
            cpu: "800m"
          limits: 
            memory: "1500Mi"
            cpu: "1600m"    
        args: 
        - -cpus
        - "2"
        - -mem-total
        - "2000Mi"
        - -mem-alloc-size
        - "100Mi"
        - -mem-alloc-sleep
        - "1s"